public class JLPT_Lists {
    public static String[][] n5List(){
        String[][] n5Verbs = { {"浴びる","あびる","Ichidan verb","to dash over oneself (e.g. water),to take (e.g. shower),to bask in (e.g. the sun)to bathe in,"},
        {"上げる","あげる","Ichidan verb","to raise,to elevate,to do up (one's hair)to fly (a kite,"},
        {"開ける","あける","Ichidan verb","to open (a door,etc.),to unwrap (e.g. parcelpackage),"},
        {"開く","ひらく","Godan verb","to open,to undo,to unsealto unpack,"},
        {"洗う","あらう","Godan verb","to wash,to cleanse,to rinseto inquire into,"},
        {"歩く","あるく","Godan verb","to walk,"},
        {"遊ぶ","あそぶ, あすぶ","Godan verb","to play (games,sports),to enjoy oneselfto have a good time,"},
        {"会う","あう","Godan verb","to meet,to encounter,to seeto have an accident,"},
        {"違う","ちがう","Godan verb","to differ (from),to be different,to be distinctto be unlike,"},
        {"出す","だす","Godan verb","to take out,to get out,to put outto reveal,"},
        {"出かける","でかける","Ichidan verb","to go out (e.g. on an excursion or outing),to leave,to departto start,"},
        {"出る","でる","Ichidan verb","to leave,to exit,to go outto come out,"},
        {"吹く","ふく","Godan verb","to blow (of the wind),to blow (one's breath),to breathe outto blow on (hot tea,"},
        {"降る","ふる","Godan verb","to fall (of rain,snow,ashetc.),"},
        {"入る","いる","Godan verb","to enter,to go in,to get into come in,"},
        {"始まる","はじまる","Godan verb","to begin,to start,to commenceto happen (again),"},
        {"履く","はく","Godan verb","to put on (lower-body clothing,e.g. pants,skirtfootwear),"},
        {"話す","はなす","Godan verb","to talk,to speak,to converseto chat,"},
        {"晴れる","はれる","Ichidan verb","to clear up,to clear away,to be sunnyto stop raining,"},
        {"張る","はる","Godan verb","to stick,to paste,to affixto stretch,"},
        {"走る","はしる","Godan verb","to run,to run (of a vehicle),to driveto travel,"},
        {"働く","はたらく","Godan verb","to work,to labor,to labourto function,"},
        {"弾く","はじく","Godan verb","to flip,to snap,to flickto repel,"},
        {"行く","いく, ゆく, イク","Godan verb","to go,to move (towards),to head (towards)to leave (for),"},
        {"入れる","いれる","Ichidan verb","to put in,to let in,to take into bring in,"},
        {"要る","いる","Godan verb","to be needed,to be necessary,to be requiredto be wanted,"},
        {"居る","いる","Ichidan verb","to be (of animate objects),to exist,to stayto be ...-ing,"},
        {"言う","いう, ゆう","Godan verb","to say,to utter,to declareto name,"},
        {"帰る","かえる","Godan verb","to return,to come home,to go hometo go back,"},
        {"返す","かえす","Godan verb","to return (something),to restore,to put backto turn over,"},
        {"掛かる","かかる","Godan verb","to take (a resource,e.g. time or money),to hangto come into view,"},
        {"掛ける","かける","Ichidan verb","to hang up (e.g. a coat,a picture on the wall),to let hangto suspend (from),"},
        {"書く","かく","Godan verb","to write,to compose,to pento draw,"},
        {"借りる","かりる","Ichidan verb","to borrow,to have a loan,to rentto hire,"},
        {"貸す","かす","Godan verb","to lend,to loan,to rent outto hire out,"},
        {"買う","かう","Godan verb","to buy,to purchase,to value (highly)to think highly of,"},
        {"消す","けす","Godan verb","to erase,to rub out,to rub offto cross out,"},
        {"消える","きえる","Ichidan verb","to disappear,to vanish,to go out of sightto go away,"},
        {"聞く","きく","Godan verb","to hear,to listen (e.g. to music),to askto enquire,"},
        {"切る","きる","Godan verb","to cut,to cut through,to perform (surgery)to sever (connections,"},
        {"着る","きる","Ichidan verb","to wear (from the shoulders down),to put on,to take (the blameresponsibility),"},
        {"困る","こまる","Godan verb","to be troubled,to have difficulty,to be in a fixto be at a loss,"},
        {"答える","こたえる","Ichidan verb","to answer,to reply,"},
        {"曇る","くもる","Godan verb","to get cloudy,to cloud over,to become overcastto cloud up,"},
        {"来る","くる","Kuru verb - special class, auxiliary verb, intransitive verb","to come (spatially or temporally),to approach,to arriveto come back,"},
        {"曲がる","まがる","Godan verb","to bend,to curve,to warpto wind,"},
        {"待つ","まつ","Godan verb","to wait,to await,to look forward toto anticipate,"},
        {"磨く","みがく","Godan verb","to polish,to shine,to burnishto scour,"},
        {"見る","みる","Ichidan verb","to see,to look,to watchto view,"},
        {"見せる","みせる","Ichidan verb","to show,to display,to make (something or someone) look ...to present an appearance of ...,"},
        {"持つ","もつ","Godan verb","to hold (in one's hand),to take,to carryto possess,"},
        {"鳴く","なく","Godan verb","to make sound (of an animal),to call,to cryto whine,"},
        {"無くす","なくす","Godan verb","to lose (something),to get rid of,to eliminateto remove,"},
        {"並べる","ならべる","Ichidan verb","to line up,to set up,to arrange in a lineto enumerate,"},
        {"並ぶ","ならぶ","Godan verb","to line up,to stand in a line,to rivalto match,"},
        {"習う","ならう","Godan verb","to take lessons in,to be taught,to learn (from a teacher)to study (under a teacher),"},
        {"寝る","ねる","Ichidan verb","to sleep (lying down),to go to bed,to lie in bedto lie down,"},
        {"上る","のぼる","Godan verb","to ascend,to go up,to climbto ascend (as a natural process,"},
        {"飲む","のむ","Godan verb","to drink,to gulp,to swallowto take (medicine),"},
        {"乗る","のる, ノる","Godan verb","to get on (train,plane,busship,"},
        {"脱ぐ","ぬぐ","Godan verb","to take off (clothes,shoes,etc.)to undress,"},
        {"覚える","おぼえる","Ichidan verb","to memorize,to memorise,to commit to memoryto learn by heart,"},
        {"起きる","おきる","Ichidan verb","to get up,to rise,to blaze up (fire)to wake up,"},
        {"置く","おく","Godan verb","to put,to place,to leave (behind)to establish (an organization,"},
        {"降りる","おりる","Ichidan verb","to descend (e.g. a mountain),to go down,to come downto alight (e.g. from bus),"},
        {"教える","おしえる","Ichidan verb","to teach,to instruct,to tellto inform,"},
        {"押す","おす","Godan verb","to push,to thrust,to shoveto press (down),"},
        {"終わる","おわる","Godan verb","to end,to come to an end,to finishto close,"},
        {"泳ぐ","およぐ","Godan verb","to swim,to struggle through (a crowd),to make one's way through the worldto get along (in life),"},
        {"咲く","さく","Godan verb","to bloom,to flower,to blossomto open,"},
        {"差す","さす","Godan verb","to shine,to be visible,to be tinged withto rise (of water levels),"},
        {"閉まる","しまる","Godan verb","to be shut,to close,to be closedto be firm (of a body,"},
        {"閉める","しめる","Ichidan verb","to close,to shut,"},
        {"締める","しめる","Ichidan verb","to tie,to fasten,to tightento wear (necktie,"},
        {"死ぬ","しぬ, ﾀﾋぬ","Godan verb","to die,to pass away,to lose spiritto lose vigor,"},
        {"知る","しる","Godan verb","to know,to be aware (of),to be conscious (of)to learn (of),"},
        {"住む","すむ","Godan verb","to live (of humans),to reside,to inhabitto dwell,"},
        {"吸う","すう","Godan verb","to smoke,to breathe in,to inhaleto suck,"},
        {"座る","すわる","Godan verb","to sit,to squat,to assume (a position)to hold steady,"},
        {"食べる","たべる","Ichidan verb","to eat,to live on (e.g. a salary),to live offto subsist on,"},
        {"頼む","たのむ","Godan verb","to request,to beg,to askto call,"},
        {"立つ","たつ","Godan verb","to stand (up),to rise,to get to one's feetto stand on end (e.g. of hairs),"},
        {"飛ぶ","とぶ","Godan verb","to fly,to soar,to jumpto leap,"},
        {"止まる","とまる","Godan verb","to stop (moving),to come to a stop,to stop (doingworking,"},
        {"取る","とる","Godan verb","to take,to pick up,to grabto catch,"},
        {"撮る","とる","Godan verb","to take (a photograph),to record (audio or video),to filmto shoot,"},
        {"疲れる","つかれる","Ichidan verb","to get tired,to tire,to get fatiguedto become exhausted,"},
        {"使う","つかう","Godan verb","to use (a tool,method,etc.)to make use of,"},
        {"付ける","つける","Ichidan verb","to attach,to join,to connectto add,"},
        {"着く","つく","Godan verb","to arrive at,to reach,to sit onto sit at (e.g. the table),"},
        {"作る","つくる","Godan verb","to make,to produce,to manufactureto build,"},
        {"勤める","つとめる","Ichidan verb","to work (for),to be employed (at),to serve (in)to serve (as),"},
        {"生まれる","うまれる","Ichidan verb","to be born,"},
        {"売る","うる","Godan verb","to sell,to betray,to sell out (one's friendcountry,"},
        {"歌う","うたう","Godan verb","to sing,to sing of (love,beautyetc.) in a poem,"},
        {"分かる","わかる","Godan verb","to understand,to comprehend,to graspto see,"},
        {"忘れる","わすれる","Ichidan verb","to forget,to leave carelessly,to be forgetful ofto forget about,"},
        {"渡る","わたる","Godan verb","to cross over,to go across,to extendto cover,"},
        {"渡す","わたす","Godan verb","to ferry across (e.g. a river),to carry across,to traverseto lay across,"},
        {"遣る","やる, ヤる","Godan verb","to do,to undertake,to performto play (a game),"},
        {"休む","やすむ","Godan verb","to be absent,to take a day off,to restto have a break,"},
        {"呼ぶ","よぶ","Godan verb","to call out (to),to call,to invoketo summon (a doctor,"},
        {"読む","よむ","Godan verb","to read,to recite (e.g. a sutra),to chantto predict,"},
        {"有る","ある","Godan verb","to be,to exist,to liveto have,"},
        {"為る","する","auxiliary verb, intransitive verb, suru verb - included, transitive verb, suffix","to do,to carry out,to performto cause to become,"} };

        return n5Verbs;
    }
    
}
